### PR TITLE
Sometimes, you've just gotta use a 4-byte float.

### PR DESCRIPTION
**Pull request by davidbrodrick**

### CODE REVIEW

**Comment by joscha** [comment]
Nice! Can we add tests for this new data type, please?

**Comment by davidbrodrick** [comment]
Yeah sorry, I would have added those initially but somehow missed the unit test suite in the library completely until after I'd made the pull request. I'm just taking a look what I need to do to add some coverage.

**Review by joscha — COMMENTED** [review]
Looks great now, however there seems to be a rounding issue which shows up on the tests

**Comment by davidbrodrick** [comment]
Yep, I'll apply an epsilon. Ran out of time last night. Will get back to it shortly.

**Comment by davidbrodrick** [comment]
Hopefully all good now. 99.99 is IEEE 754 encoded as 99.98999786376953125 so I added an appropriate epsilon in the check. Coverage decreased because I moved the rawfloat from the deep copy comparison in the LoraMessage decode.

**Comment by joscha** [comment]
Nice work. I can merge once the tests are green.

**Comment by davidbrodrick** [comment]
Yeah I'm a bit confused. I think all test passed but it indicates a fail because of the coverage.

**Comment by joscha** [comment]
Ah yes, because of the decrease. That's fine, I'll give in to the 1% :)

**Pull request merged**
